DROP TABLE member;

CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR(12) NOT NULL PRIMARY KEY,
    MEMBER_PW VARCHAR(12) NOT NULL,
    MEMBER_NAME VARCHAR(20) NOT NULL,
    MEMBER_EMAIL VARCHAR(30) NOT NULL
);

DESC member;