-- memberdb 가 존재할 경우 재생성
DROP DATABASE MEMBERDB;
CREATE DATABASE MEMBERDB DEFAULT CHARACTER SET UTF8;

-- 테이블을 생성하기 위해 memberdb 사용
USE MEMBERDB;

-- member 테이블 사용
CREATE TABLE MEMBER
(
	USER_ID    VARCHAR(20) PRIMARY KEY,
	PASSWORD   VARCHAR(32) NOT NULL,
	IS_ADMIN   TINYINT( 1) NOT NULL DEFAULT 0,
	NAME       VARCHAR(60) NOT NULL,
	SCHOOL     VARCHAR(60) NOT NULL,
	DEPARTMENT VARCHAR(60) NOT NULL,
	STUDENT_ID VARCHAR(32) NOT NULL
);
