-- If memberdb exist, delete and recreate it.
DROP DATABASE MEMBERDB;
CREATE DATABASE MEMBERDB DEFAULT CHARACTER SET UTF8;

-- Use memberdb to create member table.
USE MEMBERDB;

-- Create a member table to store users.
CREATE TABLE MEMBER
(
	USER_ID    VARCHAR(20) PRIMARY KEY,
	PASSWORD   VARCHAR(32) NOT NULL,
	IS_ADMIN   TINYINT( 1) NOT NULL DEFAULT 0,
	NAME       VARCHAR(60) NOT NULL,
	SCHOOL     VARCHAR(60) NOT NULL,
	DEPARTMENT VARCHAR(60) NOT NULL,
	STUDENT_ID VARCHAR(32) NOT NULL
);
