//
// Created by HM on 2021/08/20.
//

#ifndef MYEONGPUM_CPP_PROGRAMMING_RANDOM_H
#define MYEONGPUM_CPP_PROGRAMMING_RANDOM_H

#define RAND_MAX 32767
#define GET_RAND 10

#endif //MYEONGPUM_CPP_PROGRAMMING_RANDOM_H
